
services:
  selenium-hub-F:
    image: selenium/hub:4.8.0
    container_name: selenium-hub-F
    networks:
      - mynetwork
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.8.0
    depends_on:
      - selenium-hub-F
    networks:
      - mynetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-F
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.8.0
    depends_on:
      - selenium-hub-F
    networks:
      - mynetwork
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-F
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  mysql:
    image: mysql:8.0
    container_name: mysql-A
    restart: always
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpwd
    ports:
      - "3307:3307"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: absa-assess-java
    networks:
      - mynetwork
    environment:
      SELENIUM_HUB_URL: "http://selenium-hub-F:4444/wd/hub"
      DB_URL: "jdbc:mysql://mysql:3307/testdb"
      DB_USER: "testuser"
      DB_PASSWORD: "testpwd"
    depends_on:
      - selenium-hub-F
      - mysql
    volumes:
      - ./target/screenshots:/app/target/screenshots

networks:
  mynetwork:
